### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by blakeembrey** [types/env-electron#12]
@unional Are you still using this? I noticed some updates have some through DefinitelyTyped by @miniak - see https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/github-electron/github-electron.d.ts. @miniak Is there anything we can do to help you perhaps?

**Comment by unional** [comment]
I'm not using it right now. Will probably do so soon.

**Comment by miniak** [comment]
I have only been updating DT, it's up to date for Electron 1.4.1

**Comment by miniak** [comment]
The review process became much faster recently there

**Comment by miniak** [comment]
Electron is working on providing an official electron.d.ts (automatically generated from the API docs) electron/electron#4875. Please raise any concerns / ideas there.
