### ISSUE TITLE
Try to remove hard dependency on ambient Node.js shape

### ISSUE THREAD

**Issue by blakeembrey** [types/env-electron#2]
This one is tricky, but generally valuable. Currently the type definition is directly tied to the current Node.js type definition _shape_ on DefinitelyTyped. I'd love to move away from relying on ambient shapes and instead rely on the actual exposed types. E.g. Change from relying on `NodeJS.EventEmitter` to `import { EventEmitter } from 'events'`. Basically, making dependencies explicit and mirroring what exists at runtime instead of relying on implicit and ambient interfaces.

**Comment by OlsonDev** [comment]
In your example, you say `import { EventEmitter } from 'events'` -- did you actually mean `import * as EventEmitter from 'events'`?

I'm only guessing, based on looking at https://nodejs.org/api/events.html, wherein JavaScript land it's:

``` javascript
const EventEmitter = require('events');
class MyEmitter extends EventEmitter {}
```

Just trying to wrap my head around this idea. :smile:

**Comment by blakeembrey** [comment]
Actually, my import works fine. I have no idea when `node` aliased to `module.exports`, guess I've been using it long enough - well before that was a thing. But yes, that's the idea.

**Comment by blakeembrey** [comment]
Huh, looks like it was Node <= 0.10 that did those exports - https://github.com/nodejs/node/blob/master/lib/events.js#L10.

**Comment by OlsonDev** [comment]
So, early 2013. :smile: Either way, if Node is allowing you to name them whatever you want via `module.exports`, I'm guessing `.d.ts` files should rename them however they want? Not sure if it matters...?

**Comment by blakeembrey** [comment]
Yeah, since before then :smile: Anyway, happy to use `import EventEmitter = require('events')` instead, for consistency with current node versions. I still develop against node 0.10, so there's that I guess :stuck_out_tongue_closed_eyes: 

> Either way, if Node is allowing you to name them whatever you want via module.exports, I'm guessing .d.ts files should rename them however they want? Not sure if it matters...?

I'm confused by what this means?

**Comment by OlsonDev** [comment]
Uhhh... I'm confused myself. :laughing:

Is there a syntax to use non-ambient/global declarations in your own `.d.ts` file? I thought I saw something in the form `import EventEmitter = require('events')` or `import { EventEmitter } from 'events'`  in a `.d.ts` file but now I believe I'm mistaken.

**Comment by blakeembrey** [comment]
Yes, you can do it. But it needs to be within `declare module '...'` if it's an ambient declaration or at the top level if it's an external module. In this case we probably want to do it inside of `declare module '...'`, but I understand it can be tricky to make that work. It's an issue with how TypeScript detects whether files are "global" or not so they restrict top-level imports in ambient definitions.

Once the first refactors are done, I'll take a look into the interfaces and see if there's a way to keep integrity and fix the leakiness.

**Comment by miniak** [comment]
Electron is working on providing an official electron.d.ts (automatically generated from the API docs) https://github.com/electron/electron/issues/4875. Please raise any concerns / ideas there.
