### ISSUE TITLE
Consider removing the node module augmentation

### ISSUE THREAD

**Issue by blakeembrey** [types/env-electron#3]
https://github.com/typed-typings/env-electron/blob/master/index.d.ts#L4226-L4228. I can't see any actual value coming from that, and I feel like it's very brittle - the users node typings may not have this interface exposed ambiently.

**Comment by unional** [comment]
4226-4228? Its empty~

**Comment by OlsonDev** [comment]
I'm guessing he meant this:

``` typescript
interface NodeRequireFunction {
    (moduleName: 'electron'): Electron.ElectronMainAndRenderer;
}
```

**Comment by fank** [comment]
https://github.com/typed-typings/env-electron/blob/0185a1bdb5bb1d31197e9d4001f904c3d66bba83/index.d.ts#L4226-L4228

**Comment by blakeembrey** [comment]
Haha, sorry. Thanks @Fank. Should have grabbed the commit links instead of `master`.
