### ISSUE TITLE
Update definitions to v0.37.6

### ISSUE THREAD

**Issue by OlsonDev** [types/env-electron#6]
Relevant [changelog notes](https://github.com/electron/electron/releases):
- [commit](https://github.com/electron/electron/commit/884c9cc2f551d2146ef57fa48de98d80cb10cad1) Add isMainFrame parameter to did-fail-load event of WebContents.
- [commit](https://github.com/electron/electron/commit/3fb39ad3ef26b8556bbd2699b0f9e28d3c07e6eb#diff-9a3021541e4f1fb544254a6f7abaadefR449) Add statusLine property to webRequest.OnHeadersReceived API's responseHeaders object.
- [commit](https://github.com/electron/electron/commit/d156846036a3dc3fba67f6d799a2dfbb002d0571#diff-bb5020d9a1ac3472a273f5345838ff02R182) Add backgroundThrottling option to webPreferences of BrowserWindow.
- [commit](https://github.com/electron/electron/commit/50f51899de609d75ea7a33dfb531b79f630d0780) Add resourceType parameter to did-get-response-details event of WebContents.

**Comment by OlsonDev** [comment]
I actually didn't add `statusLine` in `session.webRequest.onHeadersReceived`'s `responseHeaders` object because the entire `webRequest` is just marked as `any` right now. I figured documenting that should be deferred to another issue; see #7.

**Comment by miniak** [comment]
https://github.com/typed-typings/env-electron/commit/75e9121b3b8ca6b28fe306ea236e31379f3de495

**Comment by miniak** [comment]
You forgot to add changes in web-contents, you have only added changes to webview. Also the isMainFrame argument only seems to be added to web-contents, not webview (at least according to the docs)

**Comment by OlsonDev** [comment]
Thanks for catching that. I did test `<webview>` just now; the `'did-fail-load'` event arg does indeed have a `isMainFrame` boolean member. Seems their docs are wrong. [Here's the code](https://github.com/electron/electron/blob/a07612c1eda9452a3c0e659db479fae7f7773d4d/lib/renderer/web-view/guest-view-internal.js#L11) that generates the event object and dispatches the event:

``` javascript
var WEB_VIEW_EVENTS = {
  // snip
  'did-fail-load': ['errorCode', 'errorDescription', 'validatedURL', 'isMainFrame'],
  // snip
}

// snip

var dispatchEvent = function (webView, eventName, eventKey, ...args) {
  var domEvent, f, i, j, len, ref1
  if (DEPRECATED_EVENTS[eventName] != null) {
    dispatchEvent.apply(null, [webView, DEPRECATED_EVENTS[eventName], eventKey].concat(args))
  }
  domEvent = new Event(eventName)
  ref1 = WEB_VIEW_EVENTS[eventKey]
  for (i = j = 0, len = ref1.length; j < len; i = ++j) {
    f = ref1[i]
    domEvent[f] = args[i]
  }
  webView.dispatchEvent(domEvent)
  if (eventName === 'load-commit') {
    return webView.onLoadCommit(domEvent)
  }
}
```

**Comment by miniak** [comment]
I have back-ported the changes to the original DT version: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9016
We should let the original authors know that we have a new version in here.

**Comment by miniak** [comment]
Can you create a PR to fix the Electron documentation?

**Comment by OlsonDev** [comment]
I actually have to get going to a family function right now and have plans the rest of the weekend. I can this week sometime or if you want to, go for it.

**Comment by miniak** [comment]
I'll create the docs update PR

**Comment by miniak** [comment]
https://github.com/electron/electron/pull/5184
